version: '3.8'

services:
  mysql:
    image: mysql:8.0.17
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user_prueba
      MYSQL_PASSWORD: user_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
      